'use client';
import { Poppins } from 'next/font/google';
import './globals.css';
import { motion } from 'framer-motion';
import ParticlesBG from './components/layots/Particles';

const poppins = Poppins({
    variable: '--font-poppins',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    display: 'swap',
    subsets: ['latin'],
});

const metadata = {
    title: 'Tracker',
    description: 'Generated by Towikk',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <motion.body
                className={`${poppins.variable} antialiased w-full overflow-hidden origin-center bg-black  lg:mx-auto`}
                animate={{ clipPath: 'circle(110% at 10%)' }}
                onAnimationComplete={() =>
                    (document.body.style.overflow = 'unset')
                }
                transition={{ duration: 2, delay: 0.5 }}
            >
                <ParticlesBG />
                {children}
            </motion.body>
        </html>
    );
}
