import { Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
    variable: '--font-poppins',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    display: 'swap',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Tracker',
    description: 'Generated by Towikk',
};

export default function RootLayout({ children }) {
    return <html lang="en">{children}</html>;
}
